export const Details = [
    {
        id:0,
        address: "Mangaldai",
        date: "16-02-2022",
        email: "afridihannan325@gmail.com",
        name: "Hannan Afridi",
        phone: "+91 8751869389",
        platform: "Instagram",
        postal: "784125",
        screenshots: "hh",
        subject: "Smoking",
        summary: "None",
        type: "Cyberstalking",
    },
    {
        id:1,
        address: "Guwahati",
        date: "16-02-2022",
        email: "afridihannan7809@gmail.com",
        name: "Afridi Hannan",
        phone: "+91 8751832434",
        platform: "Facebook",
        postal: "7841252",
        screenshots: "me",
        subject: "Drinking",
        summary: "None",
        type: "Exclusion",
    }
]