export const CREATE_REPORT_REQUEST = "CREATE_REPORT_REQUEST";
export const CREATE_REPORT_SUCCESS = "CREATE_REPORT_SUCCESS";
export const CREATE_REPORT_FAIL = "CREATE_REPORT_FAIL";
export const CREATE_REPORT_RESET = "CREATE_REPORT_RESET";

export const ALL_REPORTS_REQUEST = "ALL_REPORTS_REQUEST";
export const ALL_REPORTS_SUCCESS = "ALL_REPORTS_SUCCESS";
export const ALL_REPORTS_FAIL = "ALL_REPORTS_FAIL";

export const UPDATE_REPORT_REQUEST = "UPDATE_REPORT_REQUEST";
export const UPDATE_REPORT_SUCCESS = "UPDATE_REPORT_SUCCESS";
export const UPDATE_REPORT_RESET = "UPDATE_REPORT_RESET";
export const UPDATE_REPORT_FAIL = "UPDATE_REPORT_FAIL";

export const REPORT_DETAILS_REQUEST = "REPORT_DETAILS_REQUEST";
export const REPORT_DETAILS_SUCCESS = "REPORT_DETAILS_SUCCESS";
export const REPORT_DETAILS_FAIL = "REPORT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

